version: '3.9'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - 3002:3002
      - 9229:9229
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15 # версия PostgreSQL
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin # имя пользователя
      POSTGRES_PASSWORD: 123123 # пароль
      POSTGRES_DB: donation # база данных
    ports:
      - '5432:5432' # проброс порта на хост
    volumes:
      - pgdata:/var/lib/postgresql/data # сохранение данных

volumes:
  pgdata:
