name: GitHub Actions Donation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [24.x]
    env:
      APP_PORT: 3002
      CLIENT_URL: http://localhost:3000
      COOKIE_NAME: access_token
      COOKIE_SECRET_KEY: lgfd,gdlkdlgldfg
      JWT_SECRET_KEY: dsjksdjdksjfdskj
      DATABASE_URL: postgresql://admin:123123@localhost:5432/donation
      SMTP_USER: youtonlive@gmail.com
      SMTP_PASS: 'bwjz puqf bvek cobo'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      - name: install modules
        run: yarn
      - name: generate prisma types
        run: npx prisma generate
      - name: build project
        run: yarn build
      - name: unit test
        run: yarn test
      - name: Start database
        run: docker compose up -d
      - name: Wait for Database
        run: sleep 10
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
      - name: e2e test
        run: yarn test:e2e
